# Your API Key here:
DEEPSEEK_API_KEY = "YOUR API KEY"
GEMINI_API_KEY = "YOUR API KEY"
GROQ_API_KEY = "YOUR API KEY"
BAIDU_API_KEY = "YOUR API KEY"
BAIDU_SECRETE_API_KEY = "YOUR API KEY"
QIANWEN_API_KEY = "YOUR API KEY"
MOONSHOT_API_KEY = "YOUR API KEY"
BING_SEARCH_API_KEY = "YOUR API KEY"



