graph TD
哺乳动物["ANIMAL:哺乳动物"]
恒温["TRAITS:恒温"]
有毛发["TRAITS:有毛发"]
哺乳腺["TRAITS:哺乳腺"]
胎生["TRAITS:胎生"]
鸟类["ANIMAL:鸟类"]
羽毛["TRAITS:羽毛"]
喙["TRAITS:喙"]
卵生["TRAITS:卵生"]
飞行能力["TRAITS:飞行能力"]
爬行动物["ANIMAL:爬行动物"]
冷血["TRAITS:冷血"]
鳞片["TRAITS:鳞片"]
卵生或胎生["TRAITS:卵生或胎生"]
四肢适应陆地生活["TRAITS:四肢适应陆地生活"]
两栖动物["ANIMAL:两栖动物"]
湿润的皮肤["TRAITS:湿润的皮肤"]
幼体水生["TRAITS:幼体水生"]
成体陆生["TRAITS:成体陆生"]
呼吸方式的多样性["TRAITS:呼吸方式的多样性"]
鱼类["ANIMAL:鱼类"]
鳃呼吸["ACTION:鳃呼吸"]
流线型体型["TRAITS:流线型体型"]
多样化的繁殖方式["TRAITS:多样化的繁殖方式"]
三文鱼["ANIMAL:三文鱼"]
强健的肌肉["TRAITS:强健的肌肉"]
逆流而上["ACTION:逆流而上"]
迁徙过程["EVENT:迁徙过程"]
鳄鱼["ANIMAL:鳄鱼"]
繁殖策略["ACTION:繁殖策略"]
热带水域["OTHER:热带水域"]
湿地环境["OTHER:湿地环境"]
热带雨林["OTHER:热带雨林"]
角蝰["ANIMAL:角蝰"]
鳞片结构["TRAITS:鳞片结构"]
鼻孔位置["TRAITS:鼻孔位置"]
体温调节机制["TRAITS:体温调节机制"]
毒液["SUBSTANCE:毒液"]
沙漠生态系统["OTHER:沙漠生态系统"]
变色龙["ANIMAL:变色龙"]
皮肤颜色变化能力["TRAITS:皮肤颜色变化能力"]
粘性舌头["TRAITS:粘性舌头"]
可独立移动的眼睛["TRAITS:可独立移动的眼睛"]
伪装["ACTION:伪装"]
社交["ACTION:社交"]
温度调节["ACTION:温度调节"]
捕食["ACTION:捕食"]
防御["ACTION:防御"]
沙漠边缘["OTHER:沙漠边缘"]
哺乳动物 --> |"[1]"| 恒温
    linkStyle 0 stroke-dasharray: 5 2,font-family:'MesloLGLDZ Nerd Font Propo',stroke:#FFFFFF,stroke-width:2px,font-size:25px,padding:2px;
哺乳动物 --> |"[2]"| 有毛发
    linkStyle 1 stroke-dasharray: 5 3,font-family:'MesloLGLDZ Nerd Font Propo',stroke:#FFFFFF,stroke-width:2px,font-size:25px,padding:2px;
哺乳动物 --> |"[3]"| 哺乳腺
    linkStyle 2 stroke-dasharray: 5 1,font-family:'MesloLGLDZ Nerd Font Propo',stroke:#FFFFFF,stroke-width:2px,font-size:25px,padding:2px;
哺乳动物 --> |"[4]"| 胎生
    linkStyle 3 stroke-dasharray: 5 2,font-family:'MesloLGLDZ Nerd Font Propo',stroke:#FFFFFF,stroke-width:2px,font-size:25px,padding:2px;
鸟类 --> |"[5]"| 羽毛
    linkStyle 4 stroke-dasharray: 5 1,font-family:'MesloLGLDZ Nerd Font Propo',stroke:#FFFFFF,stroke-width:2px,font-size:25px,padding:2px;
鸟类 --> |"[6]"| 喙
    linkStyle 5 stroke-dasharray: 5 2,font-family:'MesloLGLDZ Nerd Font Propo',stroke:#FFFFFF,stroke-width:2px,font-size:25px,padding:2px;
鸟类 --> |"[7]"| 卵生
    linkStyle 6 stroke-dasharray: 5 3,font-family:'MesloLGLDZ Nerd Font Propo',stroke:#FFFFFF,stroke-width:2px,font-size:25px,padding:2px;
鸟类 --> |"[8]"| 飞行能力
    linkStyle 7 stroke-dasharray: 5 0,font-family:'MesloLGLDZ Nerd Font Propo',stroke:#FFFFFF,stroke-width:2px,font-size:25px,padding:2px;
爬行动物 --> |"[9]"| 冷血
    linkStyle 8 stroke-dasharray: 5 2,font-family:'MesloLGLDZ Nerd Font Propo',stroke:#FFFFFF,stroke-width:2px,font-size:25px,padding:2px;
爬行动物 --> |"[10]"| 鳞片
    linkStyle 9 stroke-dasharray: 5 2,font-family:'MesloLGLDZ Nerd Font Propo',stroke:#FFFFFF,stroke-width:2px,font-size:25px,padding:2px;
爬行动物 --> |"[11]"| 卵生或胎生
    linkStyle 10 stroke-dasharray: 5 2,font-family:'MesloLGLDZ Nerd Font Propo',stroke:#FFFFFF,stroke-width:2px,font-size:25px,padding:2px;
爬行动物 --> |"[12]"| 四肢适应陆地生活
    linkStyle 11 stroke-dasharray: 5 2,font-family:'MesloLGLDZ Nerd Font Propo',stroke:#FFFFFF,stroke-width:2px,font-size:25px,padding:2px;
两栖动物 --> |"[13]"| 湿润的皮肤
    linkStyle 12 stroke-dasharray: 5 2,font-family:'MesloLGLDZ Nerd Font Propo',stroke:#FFFFFF,stroke-width:2px,font-size:25px,padding:2px;
两栖动物 --> |"[14]"| 幼体水生
    linkStyle 13 stroke-dasharray: 5 3,font-family:'MesloLGLDZ Nerd Font Propo',stroke:#FFFFFF,stroke-width:2px,font-size:25px,padding:2px;
两栖动物 --> |"[15]"| 成体陆生
    linkStyle 14 stroke-dasharray: 5 3,font-family:'MesloLGLDZ Nerd Font Propo',stroke:#FFFFFF,stroke-width:2px,font-size:25px,padding:2px;
两栖动物 --> |"[16]"| 呼吸方式的多样性
    linkStyle 15 stroke-dasharray: 5 2,font-family:'MesloLGLDZ Nerd Font Propo',stroke:#FFFFFF,stroke-width:2px,font-size:25px,padding:2px;
鱼类 --> |"[17]"| 鳞片
    linkStyle 16 stroke-dasharray: 5 2,font-family:'MesloLGLDZ Nerd Font Propo',stroke:#FFFFFF,stroke-width:2px,font-size:25px,padding:2px;
鱼类 --> |"[18]"| 鳃呼吸
    linkStyle 17 stroke-dasharray: 5 1,font-family:'MesloLGLDZ Nerd Font Propo',stroke:#FFFFFF,stroke-width:2px,font-size:25px,padding:2px;
鱼类 --> |"[19]"| 流线型体型
    linkStyle 18 stroke-dasharray: 5 2,font-family:'MesloLGLDZ Nerd Font Propo',stroke:#FFFFFF,stroke-width:2px,font-size:25px,padding:2px;
鱼类 --> |"[20]"| 多样化的繁殖方式
    linkStyle 19 stroke-dasharray: 5 1,font-family:'MesloLGLDZ Nerd Font Propo',stroke:#FFFFFF,stroke-width:2px,font-size:25px,padding:2px;
三文鱼 --> |"[21]"| 流线型体型
    linkStyle 20 stroke-dasharray: 5 2,font-family:'MesloLGLDZ Nerd Font Propo',stroke:#FFFFFF,stroke-width:2px,font-size:25px,padding:2px;
三文鱼 --> |"[22]"| 强健的肌肉
    linkStyle 21 stroke-dasharray: 5 2,font-family:'MesloLGLDZ Nerd Font Propo',stroke:#FFFFFF,stroke-width:2px,font-size:25px,padding:2px;
三文鱼 --> |"[23]"| 鳞片
    linkStyle 22 stroke-dasharray: 5 3,font-family:'MesloLGLDZ Nerd Font Propo',stroke:#FFFFFF,stroke-width:2px,font-size:25px,padding:2px;
三文鱼 --> |"[24]"| 鳃呼吸
    linkStyle 23 stroke-dasharray: 5 1,font-family:'MesloLGLDZ Nerd Font Propo',stroke:#FFFFFF,stroke-width:2px,font-size:25px,padding:2px;
三文鱼 --> |"[25]"| 逆流而上
    linkStyle 24 stroke-dasharray: 5 2,font-family:'MesloLGLDZ Nerd Font Propo',stroke:#FFFFFF,stroke-width:2px,font-size:25px,padding:2px;
三文鱼 --> |"[26]"| 迁徙过程
    linkStyle 25 stroke-dasharray: 5 1,font-family:'MesloLGLDZ Nerd Font Propo',stroke:#FFFFFF,stroke-width:2px,font-size:25px,padding:2px;
鳄鱼 --> |"[27]"| 鳞片
    linkStyle 26 stroke-dasharray: 5 2,font-family:'MesloLGLDZ Nerd Font Propo',stroke:#FFFFFF,stroke-width:2px,font-size:25px,padding:2px;
鳄鱼 --> |"[28]"| 繁殖策略
    linkStyle 27 stroke-dasharray: 5 1,font-family:'MesloLGLDZ Nerd Font Propo',stroke:#FFFFFF,stroke-width:2px,font-size:25px,padding:2px;
鳄鱼 --> |"[29]"| 热带水域
    linkStyle 28 stroke-dasharray: 5 3,font-family:'MesloLGLDZ Nerd Font Propo',stroke:#FFFFFF,stroke-width:2px,font-size:25px,padding:2px;
鳄鱼 --> |"[30]"| 湿地环境
    linkStyle 29 stroke-dasharray: 5 2,font-family:'MesloLGLDZ Nerd Font Propo',stroke:#FFFFFF,stroke-width:2px,font-size:25px,padding:2px;
鳄鱼 --> |"[31]"| 热带雨林
    linkStyle 30 stroke-dasharray: 5 3,font-family:'MesloLGLDZ Nerd Font Propo',stroke:#FFFFFF,stroke-width:2px,font-size:25px,padding:2px;
角蝰 --> |"[32]"| 鳞片结构
    linkStyle 31 stroke-dasharray: 5 2,font-family:'MesloLGLDZ Nerd Font Propo',stroke:#FFFFFF,stroke-width:2px,font-size:25px,padding:2px;
角蝰 --> |"[33]"| 鼻孔位置
    linkStyle 32 stroke-dasharray: 5 3,font-family:'MesloLGLDZ Nerd Font Propo',stroke:#FFFFFF,stroke-width:2px,font-size:25px,padding:2px;
角蝰 --> |"[34]"| 体温调节机制
    linkStyle 33 stroke-dasharray: 5 3,font-family:'MesloLGLDZ Nerd Font Propo',stroke:#FFFFFF,stroke-width:2px,font-size:25px,padding:2px;
角蝰 --> |"[35]"| 毒液
    linkStyle 34 stroke-dasharray: 5 1,font-family:'MesloLGLDZ Nerd Font Propo',stroke:#FFFFFF,stroke-width:2px,font-size:25px,padding:2px;
角蝰 --> |"[36]"| 沙漠生态系统
    linkStyle 35 stroke-dasharray: 5 2,font-family:'MesloLGLDZ Nerd Font Propo',stroke:#FFFFFF,stroke-width:2px,font-size:25px,padding:2px;
变色龙 --> |"[37]"| 皮肤颜色变化能力
    linkStyle 36 stroke-dasharray: 5 1,font-family:'MesloLGLDZ Nerd Font Propo',stroke:#FFFFFF,stroke-width:2px,font-size:25px,padding:2px;
变色龙 --> |"[38]"| 粘性舌头
    linkStyle 37 stroke-dasharray: 5 2,font-family:'MesloLGLDZ Nerd Font Propo',stroke:#FFFFFF,stroke-width:2px,font-size:25px,padding:2px;
变色龙 --> |"[39]"| 可独立移动的眼睛
    linkStyle 38 stroke-dasharray: 5 2,font-family:'MesloLGLDZ Nerd Font Propo',stroke:#FFFFFF,stroke-width:2px,font-size:25px,padding:2px;
变色龙 --> |"[40]"| 伪装
    linkStyle 39 stroke-dasharray: 5 3,font-family:'MesloLGLDZ Nerd Font Propo',stroke:#FFFFFF,stroke-width:2px,font-size:25px,padding:2px;
变色龙 --> |"[41]"| 社交
    linkStyle 40 stroke-dasharray: 5 3,font-family:'MesloLGLDZ Nerd Font Propo',stroke:#FFFFFF,stroke-width:2px,font-size:25px,padding:2px;
变色龙 --> |"[42]"| 温度调节
    linkStyle 41 stroke-dasharray: 5 3,font-family:'MesloLGLDZ Nerd Font Propo',stroke:#FFFFFF,stroke-width:2px,font-size:25px,padding:2px;
变色龙 --> |"[43]"| 捕食
    linkStyle 42 stroke-dasharray: 5 2,font-family:'MesloLGLDZ Nerd Font Propo',stroke:#FFFFFF,stroke-width:2px,font-size:25px,padding:2px;
变色龙 --> |"[44]"| 防御
    linkStyle 43 stroke-dasharray: 5 2,font-family:'MesloLGLDZ Nerd Font Propo',stroke:#FFFFFF,stroke-width:2px,font-size:25px,padding:2px;
变色龙 --> |"[45]"| 热带雨林
    linkStyle 44 stroke-dasharray: 5 3,font-family:'MesloLGLDZ Nerd Font Propo',stroke:#FFFFFF,stroke-width:2px,font-size:25px,padding:2px;
变色龙 --> |"[46]"| 沙漠边缘
    linkStyle 45 stroke-dasharray: 5 3,font-family:'MesloLGLDZ Nerd Font Propo',stroke:#FFFFFF,stroke-width:2px,font-size:25px,padding:2px;
    classDef default font-family: 'MesloLGLDZ Nerd Font Propo',fill:none,stroke:#E6E6E6,color:#EAEDED,font-size:25px,stroke-width:1px,rx:4,ry:4;
    classDef labelStyle font-size:30px,fill:#FF00FF,color:#1E8449,font-weight:bold;
    classDef edgeLabel font-family: 'MesloLGLDZ Nerd Font Propo', monospace,fill:black,stroke:black,rx:4,ry:4,font-weight:bold,font-size: 16px, color: white,padding:4px;
